In [2]:
import numpy as np

In [3]:
np.abs(-1)


np.int64(1)

In [4]:
from numpy import array, dot, sign

from numpy import *

In [5]:
list1 = [1,1.1,-5,45,3.2]
arr1 = np.array(list1)
arr1

array([ 1. ,  1.1, -5. , 45. ,  3.2])

In [6]:
list2=[[1,1.1,-5.45,3.2],[-0.5,0.33,10.12,-5]]

In [7]:
arr2= np.array(list2)
arr2

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [8]:
arr1.shape

(5,)

In [9]:
arr2.shape

(2, 4)

In [10]:
print (arr1[0])

1.0


In [11]:
print (arr1[1:3])

[ 1.1 -5. ]


In [12]:
print (arr1[-2:])

[45.   3.2]


In [13]:
arr2

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [14]:
arr2[0]

array([ 1.  ,  1.1 , -5.45,  3.2 ])

In [15]:
arr2[0][1]

np.float64(1.1)

In [16]:
arr2[0,:3]

array([ 1.  ,  1.1 , -5.45])

In [17]:
arr2[:,:3]

array([[ 1.  ,  1.1 , -5.45],
       [-0.5 ,  0.33, 10.12]])

In [18]:
mask = arr1>0

In [19]:
mask

array([ True,  True, False,  True,  True])

In [21]:
arr1[mask]

array([ 1. ,  1.1, 45. ,  3.2])

In [22]:
arr2[[True,False],:2]

array([[1. , 1.1]])

In [23]:
arr2

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [24]:
mask = arr2<0

In [25]:
mask

array([[False, False,  True, False],
       [ True, False, False,  True]])

In [26]:
arr2[mask]

array([-5.45, -0.5 , -5.  ])

In [27]:
arr2[mask] = 0
arr2

array([[ 1.  ,  1.1 ,  0.  ,  3.2 ],
       [ 0.  ,  0.33, 10.12,  0.  ]])

In [28]:
arr = np.array([1,4,9,16])

In [29]:
np.sqrt(arr)

array([1., 2., 3., 4.])

In [30]:
np.log(arr)

array([0.        , 1.38629436, 2.19722458, 2.77258872])

In [32]:
arr1=np.array([1,-1,3,5])
arr2=np.array([2,1,4,1])

In [33]:
np.maximum(arr1,arr2)

array([2, 1, 4, 5])

In [44]:
list1 = [1,1.1,-5.45,3.2]
arr1 = np.array(list1)

list2 = [[1,1.1,-5.45,3.2],[-0.5,0.33,10.12,-5]]
arr2 = np.array(list2)

In [45]:
arr1.mean()

np.float64(-0.03749999999999998)

In [46]:
print(arr2.mean())

0.5999999999999999


In [47]:
print(arr2.mean(0))

[ 0.25   0.715  2.335 -0.9  ]


In [48]:
print(arr2.mean(1))

[-0.0375  1.2375]


In [49]:
np.mean(arr2)

np.float64(0.5999999999999999)

In [50]:
arr2

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [51]:
arr2.cumsum(0)


array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [ 0.5 ,  1.43,  4.67, -1.8 ]])

In [52]:
arr2

array([[ 1.  ,  1.1 , -5.45,  3.2 ],
       [-0.5 ,  0.33, 10.12, -5.  ]])

In [54]:
mask = (arr1>0)

mask

array([ True,  True, False,  True])

In [55]:
mask.sum()

np.int64(3)

In [56]:
mask.mean()

np.float64(0.75)

In [57]:
mask.any()

np.True_

In [59]:
mask.all()

np.False_

In [60]:
arr1

array([ 1.  ,  1.1 , -5.45,  3.2 ])

In [61]:
arr1.sort()
arr1

array([-5.45,  1.  ,  1.1 ,  3.2 ])

In [62]:
tickers = np.array(['Tech','Tech','Cons','Energy', 'Financials','Financials'])

In [63]:
np.unique(tickers)

array(['Cons', 'Energy', 'Financials', 'Tech'], dtype='<U10')

In [64]:
import numpy as np
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [65]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [66]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [67]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [68]:
x @ y

array([[ 28.,  64.],
       [ 67., 181.]])

In [69]:
x.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [70]:
np.linalg.inv(x @ y)

array([[ 0.23205128, -0.08205128],
       [-0.08589744,  0.03589744]])